/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netflix;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Poyraz
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    JLabel picture;
    Timer timer;
    int x = 0;
    String[] listOfPictures = {
        "1.jpg",
        "2.jpg",
        "3.jpg",
        "4.jpg",
        "5.jpg",
        "6.jpg",
        "7.jpg",
        "8.jpg",
        "9.jpg",
        "10.jpg",
        "11.jpg",
        "12.jpg",
        "13.jpg",};

    String[] listOfGenres = {
        "Aksiyon ve Macera",
        "Bilim Kurgu ve Fantastik Yapımlar",
        "Romantik",
        "Drama",
        "Çocuk ve Aile",
        "Belgesel",
        "Komedi",
        "Aksiyon",
        "Korku",
        "Bilim ve Doğa",
        "Bilim Kurgu",
        "Gerilim",
        "Anime",
        "Reality Program",};
    ArrayList<String> listOfSelectedGenres = new ArrayList<>();
    String[] listOfMoviesHighRated;

    public MainMenu() {
        initComponents();
        slideShow();
    }

    private void slideShow() {
        picture = new JLabel();
        picture.setBounds(0, 0, 1024, 768);
        SetImageSize(listOfPictures.length - 1);

        timer = new Timer(5000, (ActionEvent e) -> {
            SetImageSize(x);
            x += 1;
            if (x >= listOfPictures.length) {
                x = 0;
            }
        });
        add(picture);
        timer.start();
        setLayout(null);
        setSize(1024, 768);
        getContentPane().setBackground(Color.DARK_GRAY);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setVisible(true);
        jPanelSignUp.setVisible(false);
    }

    public void SetImageSize(int i) {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader()
                .getResource(listOfPictures[i]));
        Image image = imageIcon.getImage();
        Image newImage = image.getScaledInstance(picture.getWidth(),
                picture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImageIcon = new ImageIcon(newImage);
        picture.setIcon(newImageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMoviesHighRated = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelSignIn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMailSignIn = new javax.swing.JTextField();
        jButtonSignIn = new javax.swing.JButton();
        jPasswordFieldSignIn = new javax.swing.JPasswordField();
        jButtonLinkToSignUp = new javax.swing.JButton();
        jPanelSignUp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMailSignUp = new javax.swing.JTextField();
        jPasswordFieldSignUpConfirmation = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordFieldSignUp = new javax.swing.JPasswordField();
        jButtonLinkToSignIn = new javax.swing.JButton();
        jButtonSignUp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jDateChooserDateOfBirth = new com.toedter.calendar.JDateChooser();
        jPanelMoviesGenres = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMovieGenres = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jButtonLinkToMoviesHighRated = new javax.swing.JButton();

        jPanelMoviesHighRated.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bu türlere göre önerilenler");
        jPanelMoviesHighRated.add(jLabel11);
        jLabel11.setBounds(90, 100, 570, 80);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanelMoviesHighRated.add(jScrollPane2);
        jScrollPane2.setBounds(150, 216, 360, 180);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NETFLIX");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanelSignIn.setBackground(new java.awt.Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanelSignIn.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("       NETFLIX-EP");
        jPanelSignIn.add(jLabel4);
        jLabel4.setBounds(150, 50, 350, 35);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Parola :");
        jPanelSignIn.add(jLabel5);
        jLabel5.setBounds(80, 190, 100, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-posta : ");
        jPanelSignIn.add(jLabel6);
        jLabel6.setBounds(76, 140, 100, 23);

        jTextFieldMailSignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldMailSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailSignInActionPerformed(evt);
            }
        });
        jPanelSignIn.add(jTextFieldMailSignIn);
        jTextFieldMailSignIn.setBounds(210, 130, 280, 40);

        jButtonSignIn.setBackground(new java.awt.Color(102, 0, 0));
        jButtonSignIn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSignIn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSignIn.setText("Giriş Yap !");
        jButtonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignInActionPerformed(evt);
            }
        });
        jPanelSignIn.add(jButtonSignIn);
        jButtonSignIn.setBounds(260, 260, 169, 92);

        jPasswordFieldSignIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordFieldSignIn.setText("");
        jPasswordFieldSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSignInActionPerformed(evt);
            }
        });
        jPanelSignIn.add(jPasswordFieldSignIn);
        jPasswordFieldSignIn.setBounds(210, 190, 280, 30);

        jButtonLinkToSignUp.setBackground(new java.awt.Color(51, 51, 51));
        jButtonLinkToSignUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLinkToSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLinkToSignUp.setText("Daha kayıt olmadın mı? ");
        jButtonLinkToSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLinkToSignUpActionPerformed(evt);
            }
        });
        jPanelSignIn.add(jButtonLinkToSignUp);
        jButtonLinkToSignUp.setBounds(220, 380, 246, 31);

        jLayeredPane1.add(jPanelSignIn, "card2");

        jPanelSignUp.setBackground(new java.awt.Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanelSignUp.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  NETFLIX-EP' ye hoş geldin!");
        jPanelSignUp.add(jLabel1);
        jLabel1.setBounds(110, 40, 430, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Parola Doğrula : ");
        jPanelSignUp.add(jLabel2);
        jLabel2.setBounds(120, 400, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-posta : ");
        jPanelSignUp.add(jLabel3);
        jLabel3.setBounds(120, 300, 100, 25);

        jTextFieldMailSignUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldMailSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailSignUpActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jTextFieldMailSignUp);
        jTextFieldMailSignUp.setBounds(290, 290, 270, 40);

        jPasswordFieldSignUpConfirmation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordFieldSignUpConfirmation.setText("");
        jPasswordFieldSignUpConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSignUpConfirmationActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jPasswordFieldSignUpConfirmation);
        jPasswordFieldSignUpConfirmation.setBounds(290, 400, 270, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Parola : ");
        jPanelSignUp.add(jLabel7);
        jLabel7.setBounds(120, 350, 100, 30);

        jPasswordFieldSignUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordFieldSignUp.setText("");
        jPasswordFieldSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSignUpActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jPasswordFieldSignUp);
        jPasswordFieldSignUp.setBounds(290, 350, 270, 30);

        jButtonLinkToSignIn.setBackground(new java.awt.Color(51, 51, 51));
        jButtonLinkToSignIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLinkToSignIn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLinkToSignIn.setText("<-GERİ");
        jButtonLinkToSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLinkToSignInActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jButtonLinkToSignIn);
        jButtonLinkToSignIn.setBounds(120, 460, 120, 40);

        jButtonSignUp.setBackground(new java.awt.Color(102, 0, 0));
        jButtonSignUp.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSignUp.setText("Şimdi Kayıt Ol !");
        jButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignUpActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jButtonSignUp);
        jButtonSignUp.setBounds(280, 460, 260, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kullanıcı Adı:");
        jPanelSignUp.add(jLabel8);
        jLabel8.setBounds(120, 180, 150, 30);

        jTextFieldUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });
        jPanelSignUp.add(jTextFieldUserName);
        jTextFieldUserName.setBounds(290, 170, 270, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Doğum Tarihi:");
        jPanelSignUp.add(jLabel9);
        jLabel9.setBounds(120, 240, 150, 30);

        jDateChooserDateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanelSignUp.add(jDateChooserDateOfBirth);
        jDateChooserDateOfBirth.setBounds(290, 230, 270, 40);

        jLayeredPane1.add(jPanelSignUp, "card3");

        jPanelMoviesGenres.setBackground(new java.awt.Color(0.0f, 0.0f, 0.0f, 0.5f));
        jPanelMoviesGenres.setLayout(null);

        jListMovieGenres.setBackground(new java.awt.Color(51, 51, 51));
        jListMovieGenres.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jListMovieGenres.setForeground(new java.awt.Color(255, 255, 255));
        jListMovieGenres.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return listOfGenres.length; }
            public String getElementAt(int i) { return listOfGenres[i]; }
        });
        jScrollPane1.setViewportView(jListMovieGenres);

        jPanelMoviesGenres.add(jScrollPane1);
        jScrollPane1.setBounds(90, 90, 500, 360);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Üç Farklı Program Türü Seçiniz:");
        jPanelMoviesGenres.add(jLabel10);
        jLabel10.setBounds(10, 20, 650, 49);

        jButtonLinkToMoviesHighRated.setBackground(new java.awt.Color(102, 0, 0));
        jButtonLinkToMoviesHighRated.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonLinkToMoviesHighRated.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLinkToMoviesHighRated.setText("DEVAM->");
        jButtonLinkToMoviesHighRated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLinkToMoviesHighRatedActionPerformed(evt);
            }
        });
        jPanelMoviesGenres.add(jButtonLinkToMoviesHighRated);
        jButtonLinkToMoviesHighRated.setBounds(190, 470, 280, 50);

        jLayeredPane1.add(jPanelMoviesGenres, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldSignUpConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSignUpConfirmationActionPerformed
        // TODO add your handling code here:
        String password = String.valueOf(jPasswordFieldSignUpConfirmation.getPassword());
        System.out.println("Kayıt sayfasındaki Parola Tekrarı: " + password);
    }//GEN-LAST:event_jPasswordFieldSignUpConfirmationActionPerformed

    private void jButtonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignInActionPerformed
        // TODO add your handling code here:
        System.out.println("Giriş sayfasındaki E-posta: " + jTextFieldMailSignIn.getText());
        String password = String.valueOf(jPasswordFieldSignIn.getPassword());
        System.out.println("Giriş sayfasındaki Parola: " + password);
        if ("".equals(jTextFieldMailSignIn.getText()) || "".equals(password)) {
            JOptionPane.showMessageDialog(null, "E-postanızı ya da parolanızı "
                    + "eksik girdiniz.\nLütfen tekrar deneyin.");
        } else {
            System.out.println("Tebrikler başarıyla giriş yaptın.");
        }
    }//GEN-LAST:event_jButtonSignInActionPerformed

    private void jPasswordFieldSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSignInActionPerformed
        // TODO add your handling code here:
        String password = String.valueOf(jPasswordFieldSignIn.getPassword());
        System.out.println("Giriş sayfasındaki Parola: " + password);
    }//GEN-LAST:event_jPasswordFieldSignInActionPerformed

    private void jButtonLinkToSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLinkToSignUpActionPerformed
        // TODO add your handling code here:
        jPanelSignIn.setVisible(false);
        jPanelSignUp.setVisible(true);
    }//GEN-LAST:event_jButtonLinkToSignUpActionPerformed

    private void jPasswordFieldSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSignUpActionPerformed
        // TODO add your handling code here:
        String password = String.valueOf(jPasswordFieldSignUp.getPassword());
        System.out.println("Kayıt sayfasındaki Parola: " + password);
    }//GEN-LAST:event_jPasswordFieldSignUpActionPerformed

    private void jButtonLinkToSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLinkToSignInActionPerformed
        // TODO add your handling code here:
        jPanelSignUp.setVisible(false);
        jPanelSignIn.setVisible(true);
    }//GEN-LAST:event_jButtonLinkToSignInActionPerformed

    private void jButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignUpActionPerformed
        // TODO add your handling code here:
        System.out.println("Kayıt sayfasındaki Kullanıcı Adı: " + jTextFieldUserName.getText());
        try {
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            String dateOfBirth = dateFormat.format(jDateChooserDateOfBirth.getDate());
            System.out.println("Kayıt sayfasındaki Doğum Tarihi: " + dateOfBirth);
        } catch (NullPointerException nullPointerException) {
            JOptionPane.showMessageDialog(null, "Lütfen doğum tarihinizi giriniz.");
        }
        System.out.println("Kayıt sayfasındaki E-posta: " + jTextFieldMailSignUp.getText());
        String password = String.valueOf(jPasswordFieldSignUp.getPassword());
        System.out.println("Kayıt sayfasındaki Parola : " + password);
        String passwordConfirmation = String.valueOf(jPasswordFieldSignUpConfirmation.getPassword());
        System.out.println("Kayıt sayfasındaki Parola Tekrarı: " + passwordConfirmation);

        if ("".equals(jTextFieldMailSignUp.getText()) || "".equals(password)
                || "".equals(jTextFieldUserName.getText())) {
            JOptionPane.showMessageDialog(null, "Kullanıcı adınızı, e-postanızı ya da"
                    + " parolanızı eksik girdiniz.\nLütfen tekrar deneyin.");
        } else if (!password.equals(passwordConfirmation)) {
            System.out.println("Parolalar aynı değil!");
            JOptionPane.showMessageDialog(null, "Parolalar aynı değil!");
        } else {
            JOptionPane.showMessageDialog(null, "Tebrikler başarıyla kayıt oldun.");
            System.out.println("Tebrikler başarıyla kayıt oldun.");
            jPanelSignUp.setVisible(false);
            jPanelMoviesGenres.setVisible(true);
        }

    }//GEN-LAST:event_jButtonSignUpActionPerformed

    private void jTextFieldMailSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMailSignInActionPerformed
        // TODO add your handling code here:
        System.out.println("Giriş sayfasındaki E-posta: " + jTextFieldMailSignIn.getText());

    }//GEN-LAST:event_jTextFieldMailSignInActionPerformed

    private void jTextFieldMailSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMailSignUpActionPerformed
        // TODO add your handling code here:
        System.out.println("Kayıt sayfasındaki E-posta: " + jTextFieldMailSignUp.getText());
    }//GEN-LAST:event_jTextFieldMailSignUpActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
        System.out.println("Kayıt ekranındaki Kullanıcı Adı: " + jTextFieldUserName.getText());
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    private void jButtonLinkToMoviesHighRatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLinkToMoviesHighRatedActionPerformed
        // TODO add your handling code here:
        if (jListMovieGenres.getSelectedValuesList().size() != 3) {
            JOptionPane.showMessageDialog(null, "Lütfen üç tane tür seçiniz!");
        } else {
            
            jListMovieGenres.getSelectedValuesList().forEach((selectedGenre) -> {
                listOfSelectedGenres.add(selectedGenre);
                
            });
            System.out.println("Seçilen film türleri: ");
            listOfSelectedGenres.forEach((genre) -> {
                System.out.println(genre);
            });
            jPanelMoviesGenres.setVisible(false);
            jPanelMoviesHighRated.setVisible(true);
        }
    }//GEN-LAST:event_jButtonLinkToMoviesHighRatedActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLinkToMoviesHighRated;
    private javax.swing.JButton jButtonLinkToSignIn;
    private javax.swing.JButton jButtonLinkToSignUp;
    private javax.swing.JButton jButtonSignIn;
    private javax.swing.JButton jButtonSignUp;
    private com.toedter.calendar.JDateChooser jDateChooserDateOfBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListMovieGenres;
    private javax.swing.JPanel jPanelMoviesGenres;
    private javax.swing.JPanel jPanelMoviesHighRated;
    private javax.swing.JPanel jPanelSignIn;
    private javax.swing.JPanel jPanelSignUp;
    private javax.swing.JPasswordField jPasswordFieldSignIn;
    private javax.swing.JPasswordField jPasswordFieldSignUp;
    private javax.swing.JPasswordField jPasswordFieldSignUpConfirmation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldMailSignIn;
    private javax.swing.JTextField jTextFieldMailSignUp;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
